dataset:
  name: xbd_flood_subset
  root_dir: "/mnt/c/Users/haddi/OneDrive/Desktop/flooding_dataset/flooding_dataset"

paths:
  images_pre: "images/pre"
  images_post: "images/post"
  labels_post: "labels/post"
  metadata_out: "data/interim/metadata.csv"

classes:
  keep:
    - "no-damage"
    - "minor-damage"
    - "major-damage"
    - "destroyed"

  ignore:
    - "un-classified"

label_map:
  no-damage: 0
  minor-damage: 1
  major-damage: 2
  destroyed: 3
